// Native theme proposals. Font registration and target compilation remain project checks.
const formats = new Set(["swiftui", "compose", "flutter"]);
export function nativeTokens(system, format) {
  if (!formats.has(format)) throw Error("Native format must be swiftui, compose or flutter");
  const roles = {
    primary: "action",
    onPrimary: "onAction",
    background: "background",
    onBackground: "text",
    surface: "surface",
    onSurface: "text",
    error: "danger",
    onError: "onDanger",
  };
  const modes = {};
  for (const mode of ["light", "dark"]) {
    const tokens = system.palette.modes[mode].tokens;
    modes[mode] = Object.fromEntries(
      Object.entries(roles).map(([name, role]) => {
        const value = tokens[role];
        if (!/^#[\da-f]{6}$/i.test(value))
          throw Error(`Missing opaque native color: ${mode}.${role}`);
        return [name, value.slice(1).toUpperCase()];
      }),
    );
  }
  // Native fonts need platform-specific face names/assets. Preserve those decisions for the app.
  const size = system.type.step0 * 16;
  if (!Number.isFinite(size) || size < 8 || size > 96) throw Error("Unsupported native body size");
  const header =
    "// Generated by Dazzler. Register licensed font assets before replacing system defaults.\n";
  if (format === "swiftui") {
    const colors = Object.entries(modes.light)
      .map(
        ([name, value]) =>
          `    static let ${name} = Color(uiColor: UIColor { traits in\n        let hex: UInt32 = traits.userInterfaceStyle == .dark ? 0x${modes.dark[name]} : 0x${value}\n        return UIColor(red: CGFloat((hex >> 16) & 255) / 255, green: CGFloat((hex >> 8) & 255) / 255, blue: CGFloat(hex & 255) / 255, alpha: 1)\n    })`,
      )
      .join("\n");
    return {
      name: "DazzlerTheme.swift",
      code:
        header +
        `import SwiftUI\nimport UIKit\n\nenum DazzlerColors {\n${colors}\n}\n\nenum DazzlerType {\n    static let body = Font.body\n    static let heading = Font.title\n}\n// iOS only: semantic fonts preserve Dynamic Type. Minimum interactive size: 44pt.\n`,
    };
  }
  if (format === "compose") {
    const schemes = Object.entries(modes)
      .map(
        ([mode, colors]) =>
          `val Dazzler${mode === "light" ? "Light" : "Dark"} = ${mode}ColorScheme(\n${Object.entries(
            colors,
          )
            .map(([name, hex]) => `    ${name} = Color(0xFF${hex})`)
            .join(",\n")}\n)`,
      )
      .join("\n\n");
    return {
      name: "DazzlerTheme.kt",
      code:
        header +
        `import androidx.compose.material3.*\nimport androidx.compose.ui.graphics.Color\nimport androidx.compose.ui.text.TextStyle\nimport androidx.compose.ui.unit.sp\n\n${schemes}\n\nval DazzlerTypography = Typography(bodyLarge = TextStyle(fontSize = ${size}.sp))\n// Bind the chosen scheme and typography through MaterialTheme. Minimum touch target: 48dp.\n`,
    };
  }
  const themes = Object.entries(modes)
    .map(
      ([mode, colors]) =>
        `final dazzler${mode === "light" ? "Light" : "Dark"} = ThemeData(\n  useMaterial3: true,\n  colorScheme: ColorScheme.fromSeed(\n    seedColor: const Color(0xFF${colors.primary}),\n    brightness: Brightness.${mode},\n  ).copyWith(\n${Object.entries(
          colors,
        )
          .filter(([name]) => !["background", "onBackground"].includes(name))
          .map(([name, hex]) => `    ${name}: const Color(0xFF${hex}),`)
          .join(
            "\n",
          )}\n  ),\n  scaffoldBackgroundColor: const Color(0xFF${colors.background}),\n  textTheme: const TextTheme(bodyLarge: TextStyle(fontSize: ${size})),\n);`,
    )
    .join("\n\n");
  return {
    name: "dazzler_theme.dart",
    code:
      header +
      `import 'package:flutter/material.dart';\n\n${themes}\n// Bind theme/darkTheme in MaterialApp. Preserve MediaQuery text scaling and 48dp targets.\n`,
  };
}
