# Dazzler native Office adapter. Original integration: Apache-2.0.
args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 1) stop('Usage: Rscript --vanilla office-chart.R OUTPUT_DIRECTORY')
root <- normalizePath(args[[1]], mustWork = TRUE)
for (pkg in c('mschart', 'officer')) if (!requireNamespace(pkg, quietly = TRUE)) stop(paste('Missing optional R package:', pkg))
if (utils::packageVersion('mschart') < '0.5.1' || utils::packageVersion('officer') < '0.7.5') stop('Requires mschart >=0.5.1 and officer >=0.7.5')
d <- read.csv(file.path(root, 'office-data.csv'), stringsAsFactors = FALSE, check.names = FALSE, na.strings = '')
o <- read.csv(file.path(root, 'office-options.csv'), stringsAsFactors = FALSE)
v <- setNames(as.list(o$value), o$key)
s <- read.csv(file.path(root, 'office-series.csv'), stringsAsFactors = FALSE)
if (!v$type %in% c('bar','line','area','scatter') || !v$format %in% c('docx','pptx')) stop('Unsupported native output')
if (!is.numeric(d$y) || any(!is.finite(d$y[!is.na(d$y)]))) stop('Y values must be finite numbers or missing')
if (v$type == 'scatter' && !is.numeric(d$x)) stop('Scatter X must be numeric')
make <- switch(v$type, bar=mschart::ms_barchart, line=mschart::ms_linechart, area=mschart::ms_areachart, scatter=mschart::ms_scatterchart)
c <- make(data=d, x='x', y='y', group='series')
c <- mschart::chart_data_fill(c, values=setNames(s$color,s$series))
c <- mschart::chart_labels(c, title=v$title, xlab=v$xLabel, ylab=v$yLabel)
ft <- officer::fp_text(font.family=v$font, font.size=11, color=v$ink)
c <- mschart::chart_theme(c, axis_text_x=ft, axis_text_y=ft, axis_title_x=ft, axis_title_y=ft, legend_text=ft, main_title=ft, chart_background=v$background, plot_background=v$background)
if (v$type == 'bar') c <- mschart::chart_settings(c, grouping='clustered', gap_width=60)
if (v$type == 'line') c <- mschart::chart_settings(c, style='lineMarker')
output <- file.path(root,paste0('chart.',v$format))
if (file.exists(output)) stop('Refusing to overwrite native output')
if (v$format == 'docx') {
 doc <- officer::read_docx()
 doc <- officer::body_add_par(doc,v$title,style='heading 1')
 doc <- mschart::body_add_chart(doc,chart=c,width=6,height=3.5)
 print(doc,target=output)
} else {
 doc <- officer::read_pptx()
 doc <- officer::add_slide(doc,layout='Title and Content',master='Office Theme')
 doc <- officer::ph_with(doc,value=v$title,location=officer::ph_location_type(type='title'))
 doc <- officer::ph_with(doc,value=c,location=officer::ph_location_type(type='body'))
 print(doc,target=output)
}
cat('Created',output,'with native chart data. Render in Office for final review.\n')
