import { build } from "esbuild";
import { mkdir, copyFile, readFile, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = fileURLToPath(new URL("../", import.meta.url));
const dest = path.join(root, "skills/dazzler-frontend/scripts/vendor");
await mkdir(dest, { recursive: true });
await build({
  absWorkingDir: root,
  entryPoints: ["tools/color-engine-entry.mjs"],
  outfile: path.join(dest, "color-engine.mjs"),
  bundle: true,
  format: "esm",
  platform: "neutral",
  target: "es2022",
  legalComments: "inline",
  banner: {
    js: "// Generated by tools/build_colors.mjs. MIT upstream code; see adjacent licenses and provenance.",
  },
});
const packages = [];
for (const [name, label] of [
  ["@ankhorage/color-theory", "ankhorage-color-theory"],
  ["culori", "culori"],
]) {
  const base = path.join(root, "node_modules", name);
  const pkg = JSON.parse(await readFile(path.join(base, "package.json"), "utf8"));
  await copyFile(path.join(base, "LICENSE"), path.join(dest, `${label}-LICENSE.txt`));
  packages.push({ name, version: pkg.version, license: pkg.license, repository: pkg.repository });
}
const bundle = await readFile(path.join(dest, "color-engine.mjs"));
await writeFile(
  path.join(dest, "provenance.json"),
  JSON.stringify(
    {
      packages,
      build:
        "esbuild 0.28.2; tools/color-engine-entry.mjs; package-lock.json pins tarball integrity",
      sha256: createHash("sha256").update(bundle).digest("hex"),
    },
    null,
    2,
  ) + "\n",
);
console.log(`Built offline color engine (${bundle.length} bytes).`);
