"""Thirty individually labelled snapshots; Word images come from actual Word renders."""
import html
def publish(docs,uis,out,version):
 e=lambda x:html.escape(str(x),quote=True);cards=[]
 for d in docs:
  for fmt in ('docx','html'):
   ident=fmt+'-'+d['id'];url=f'html/{d["id"]}.html' if fmt=='html' else f'docx/preview-{d["id"]}.html'
   if fmt=='docx':
    images=''.join(f'<img src="../previews/{ident}-p{i+1}.jpg" alt="{e(d["title"])} page {i+1}" loading="lazy">' for i in range(len(d['pages'])))
    (out/'docx'/f'preview-{d["id"]}.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>'+e(d['title'])+' — Word snapshots</title><style>body{margin:0;background:#E9E7ED;font:16px/1.5 Arial;color:#202537}header{padding:25px;max-width:1000px;margin:auto}main{max-width:1000px;margin:auto}img{display:block;width:100%;height:auto;margin:0 auto 30px}a{color:#493195}</style><header><a href="../index.html">All templates</a><h1>'+e(d['title'])+'</h1><p>Actual Microsoft Word page renders. Fictional worked example.</p><a href="'+d['id']+'.docx" download>Download editable Word document</a></header><main>'+images+'</main></html>',encoding='utf-8')
   cards.append((ident,fmt,d['id'],d['title'],d['capabilities'],url))
 for d in uis:cards.append((d['id'],'ui',d['category'],d['brand'],d['voice'],'ui/'+d['id']+'/index.html'))
 body=''.join('<article data-format="'+fmt+'"><a class="picture" href="'+url+'"><img src="previews/'+ident+'.jpg" alt="'+e(title)+' '+fmt.upper()+' snapshot" loading="lazy"></a><div><span class="tag">'+fmt.upper()+' / '+e(cat)+'</span><h2><a href="'+url+'">'+e(title)+'</a></h2><p>'+e(description)+'</p><a href="'+url+'">'+('View Word pages' if fmt=='docx' else 'Open working example')+' →</a></div></article>' for ident,fmt,cat,title,description,url in cards)
 css="*{box-sizing:border-box}body{margin:0;background:#F6F3EE;color:#202538;font:16px/1.6 'Work Sans',Arial,sans-serif}header{background:#20213C;color:#F9F6EB;padding:60px max(5%,calc((100vw - 1280px)/2))}header p{max-width:70ch}header a{color:#DCEC85}h1{font:600 clamp(40px,6vw,78px)/1.02 'Archivo',sans-serif;letter-spacing:-.055em;max-width:18ch;margin:22px 0}header strong{color:#DCEC85}main,footer{max-width:1320px;margin:auto;padding:32px 4%}.filters{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:30px}button{font:600 14px 'Work Sans',sans-serif;padding:12px 22px;border:1px solid #3E3485;background:white;color:#3E3485;cursor:pointer;border-radius:25px}button[aria-pressed=true]{background:#3E3485;color:white}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:25px}article{background:white;border:1px solid #D0CBD8;overflow:hidden}article[hidden]{display:none}article>div{padding:22px}img{width:100%;height:280px;object-fit:cover;object-position:top;display:block;background:#E8E6EF}.tag{color:#66498C;font-size:10px;font-weight:700;letter-spacing:.1em}h2{font:600 24px/1.15 'Archivo',sans-serif;margin:12px 0}a{color:#44388A;text-underline-offset:4px}h2 a{text-decoration:none;color:#202538}article p{font-size:13px}footer{font-size:13px;border-top:1px solid #B8B1C4}:focus-visible{outline:3px solid #A13256;outline-offset:4px}@media(max-width:900px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.grid{grid-template-columns:1fr}header{padding:35px 24px}img{height:320px}}"
 script="document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelectorAll('article[data-format]').forEach(x=>x.hidden=b.dataset.filter!=='all'&&x.dataset.format!==b.dataset.filter);document.getElementById('count').textContent=document.querySelectorAll('article[data-format]:not([hidden])').length+' templates shown';}));"
 (out/'index.html').write_text('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Dazzler — The showcase collection</title><link rel="stylesheet" href="fonts/fonts.css"><style>'+css+'</style></head><body><header><a href="https://jongos.github.io/Dazzler/">Dazzler field guide</a><p>THE SHOWCASE COLLECTION / '+version+'</p><h1>See what a little <strong>Dazzler</strong> can do.</h1><p>Thirty distinct starting points. Rich fictional scenarios, expressive typography, measured color, useful interactions and deliberate print layouts. Every thumbnail is a captured template, not a concept mockup.</p></header><main><div class="filters" aria-label="Template formats">'+''.join('<button data-filter="'+v+'" aria-pressed="'+str(v=='all').lower()+'">'+label+'</button>' for v,label in [('all','All 30'),('docx','Word'),('html','HTML documents'),('ui','Interfaces')])+'</div><p id="count" role="status">30 templates shown</p><div class="grid">'+body+'</div></main><footer><p>Notes and credits: original Dazzler templates and synthetic scenarios by Jon Gosier, Apache-2.0. Bundled fonts and engines retain their licenses. Word snapshots were rendered in Microsoft Word; fonts are referenced, not embedded. Interface actions are local previews.</p><a href="https://github.com/jongos/Dazzler/releases/download/v'+version+'/dazzler-templates.zip">Download the complete collection</a> · <a href="mailto:jon@filmhedge.com">Feedback</a></footer><script>'+script+'</script></body></html>',encoding='utf-8')
