// Local template behavior and responsive layout checks; use an existing Playwright runtime.
const {chromium}=require('playwright'),fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url');
(async()=>{const root=path.resolve('skills/dazzler-frontend/assets/templates'),out=path.resolve(process.argv[2]);await fs.mkdir(out,{recursive:true});
const catalog=JSON.parse(await fs.readFile(path.join(root,'catalog.json'),'utf8')),browser=await chromium.launch();const checks=[];
try{const page=await browser.newPage({acceptDownloads:true});let errors=[];page.on('pageerror',e=>errors.push(e.message));
for(const t of catalog.templates.filter(t=>t.format!=='docx')){errors=[];await page.goto(pathToFileURL(path.join(root,t.path,t.format==='ui'?'index.html':'')).href);await page.evaluate(()=>document.fonts.ready);
for(const width of [1440,390]){await page.setViewportSize({width,height:1000});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),t.id+' overflow');await page.screenshot({path:path.join(out,t.id+'-'+width+'.png'),fullPage:true});}
assert((await page.evaluate(()=>[...document.fonts].filter(f=>f.status==='loaded').length))>0,t.id+' fonts');
if(t.format==='ui'){const cfg=JSON.parse(await fs.readFile(path.join(root,t.path,'template.json'),'utf8'));assert.deepEqual(await page.locator('#template-data').evaluate(e=>JSON.parse(e.textContent)),cfg);
const save=async()=>page.locator('#dialog-save').click();
if(cfg.layout==='workspace'){await page.locator('#search').fill('no match');assert(await page.locator('#empty').isVisible());await page.locator('#search').fill('');await page.locator('[data-dialog="project"]').click();await page.locator('#entry').fill('New sample');await save();assert.equal(await page.locator('.project-row').count(),4);}
if(cfg.layout==='board'){await page.locator('#owner-filter').selectOption('Alex');assert.equal(await page.locator('.task').count(),2);await page.locator('#owner-filter').selectOption('Everyone');await page.locator('[data-dialog="task"]').click();await page.locator('#entry').fill('Review launch');await save();assert.equal(await page.locator('.task').count(),7);await page.locator('[data-move]').first().click();assert.match(await page.locator('#status').innerText(),/moved/);}
if(cfg.layout==='settings'){await page.locator('#name').fill('Taylor');assert.match(await page.locator('#dirty').innerText(),/Unsaved/);await page.locator('#settings button[type="reset"]').click();assert.equal(await page.locator('#name').inputValue(),'Alex Morgan');await page.locator('#settings button').last().click();assert.match(await page.locator('#dirty').innerText(),/Saved/);}
if(cfg.layout==='revenue'){assert((await page.locator('#revenue-metrics').innerText()).includes('$310,000.00'));await page.locator('#period').selectOption('q2');assert((await page.locator('#revenue-metrics').innerText()).includes('$175,400.00'));assert.equal(await page.locator('#revenue-table tbody tr').count(),3);const dl=page.waitForEvent('download');await page.locator('[data-action="download"]').click();const csv=await fs.readFile(await (await dl).path(),'utf8');assert(csv.includes('Apr'));assert(!csv.includes('Jan'));}
if(cfg.layout==='operations'){assert.equal(await page.locator('.ticket').count(),6);await page.locator('[data-resolve]').first().click();assert.equal(await page.locator('.ticket').count(),5);await page.locator('#show-resolved').check();assert.equal(await page.locator('.ticket').count(),6);await page.locator('#queue').selectOption('Billing');assert.equal(await page.locator('.ticket').count(),2);const dl=page.waitForEvent('download');await page.locator('[data-action="download"]').click();assert((await dl).suggestedFilename().endsWith('.csv'));}
if(cfg.layout==='reservations'){await page.locator('#guest').fill('Taylor');await page.locator('#guest-email').fill('taylor@example.com');await page.locator('input[name="time"]').first().check();await page.locator('#reservation button').click();assert((await page.locator('#dialog-content').innerText()).includes('Taylor'));await save();assert.match(await page.locator('#status').innerText(),/No table/);}
if(cfg.layout==='cafe'){await page.locator('[data-filter="Coffee"]').click();assert.equal(await page.locator('.product').count(),3);await page.locator('[data-filter="All"]').click();await page.locator('[data-add="0"]').click({clickCount:2});await page.locator('[data-add="3"]').click();assert.equal(await page.locator('#subtotal').innerText(),'$13.50');await page.locator('[data-quantity="0"][data-delta="-1"]').click();assert.equal(await page.locator('#subtotal').innerText(),'$9.00');await page.locator('[data-action="cart"]').click();await save();assert.match(await page.locator('#status').innerText(),/Nothing was sent/);}
if(cfg.layout==='menu'){await page.locator('#vegan').check();assert.equal(await page.locator('.menu-dish').count(),5);await page.locator('#menu-search').fill('lemon');assert.equal(await page.locator('.menu-dish').count(),2);await page.locator('#menu-search').fill('no such dish');assert(await page.locator('#menu-empty').isVisible());}
if(cfg.layout==='business'){await page.locator('[data-brief="0"]').click();assert((await page.locator('#dialog-content').innerText()).includes('Review checklist'));await page.keyboard.press('Escape');await page.locator('[data-approve="0"]').click();assert((await page.locator('.deliverable').first().innerText()).includes('Approved in preview'));await page.locator('[data-dialog="revision"]').click();await page.locator('#entry').fill('Clarify the headline');await save();assert((await page.locator('.deliverable').first().innerText()).includes('Clarify the headline'));}
const broken=await page.evaluate(()=>[...document.querySelectorAll('a[href^="#"]')].filter(a=>!document.getElementById(a.getAttribute('href').slice(1))).map(a=>a.getAttribute('href')));assert.deepEqual(broken,[],t.id+' broken anchors');
}
assert.deepEqual(errors,[],t.id+' page errors');checks.push({id:t.id,viewports:[1440,390],fonts:'loaded',interactionChecks:t.format==='ui'?'passed':'printable worked example'});
}
await fs.writeFile(path.join(out,'checks.json'),JSON.stringify(checks,null,2));console.log('20 HTML/UI templates passed responsive, font, context-specific interaction and data checks.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
