import {mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {render} from '../skills/dazzler-frontend/scripts/hotspots.mjs';
const root=path.resolve(process.argv[2]);await mkdir(root,{recursive:true});
const art=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 900 520"><rect width="900" height="520" fill="#F4F0E8"/><text x="40" y="50" font-family="Arial" font-size="20" fill="#20252C">ATELIER / COMMUNITY ARTS CENTER</text><g id="gallery"><rect x="40" y="90" width="390" height="220" rx="12" fill="#D7C9F5"/><text x="65" y="130" font-family="Arial" font-size="24" fill="#20252C">01 / Gallery</text><rect x="75" y="170" width="70" height="100" fill="#7048E8"/><rect x="175" y="170" width="70" height="100" fill="#B75980"/><rect x="275" y="170" width="70" height="100" fill="#58765B"/></g><g id="workshop"><rect x="460" y="90" width="400" height="220" rx="12" fill="#F1CCAC"/><text x="485" y="130" font-family="Arial" font-size="24" fill="#20252C">02 / Workshop</text><rect x="500" y="180" width="310" height="55" rx="8" fill="#A76535"/></g><g id="garden"><rect x="40" y="340" width="820" height="135" rx="12" fill="#C8DEC3"/><text x="65" y="385" font-family="Arial" font-size="24" fill="#20252C">03 / Sculpture garden</text><circle cx="660" cy="405" r="38" fill="#58765B"/><circle cx="760" cy="405" r="38" fill="#58765B"/></g></svg>`;
const artFile=path.join(root,'arts-center.svg');await writeFile(artFile,art);
const regions=[{id:'gallery',label:'Gallery',description:'Explore the current exhibition. The wide central route connects the entrance, seating and three display walls.',shape:'rect',coords:[40,90,430,310]},{id:'workshop',label:'Workshop',description:'A shared making space with a central workbench. Check the program before visiting for a class or open studio.',shape:'rect',coords:[460,90,860,310]},{id:'garden',label:'Sculpture garden',description:'An outdoor pause between activities, with sculptures and space to sit. Access follows the center’s opening schedule.',shape:'rect',coords:[40,340,860,475]}];
for(const engine of ['svg','react','vue'])await render({kind:engine==='svg'?'svg':'image',framework:engine==='svg'?'react':engine,title:'Find your space at Atelier',description:'A fictional arts-center guide. Select a room to learn what happens there.',imageAlt:'Floor plan with a gallery and workshop above a sculpture garden.',source:'Original Dazzler demonstration artwork; all places and descriptions are illustrative.',regions,width:900,height:520},artFile,path.join(root,engine));
console.log('Exported SVG, React and Vue interactive fixtures.');
