// Generated by Dazzler. Register licensed font assets before replacing system defaults.
import androidx.compose.material3.*
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.unit.sp

val DazzlerLight = lightColorScheme(
    primary = Color(0xFF7C0D98),
    onPrimary = Color(0xFFFFFFFF),
    background = Color(0xFFFAF9FF),
    onBackground = Color(0xFF18181B),
    surface = Color(0xFFEEEEF4),
    onSurface = Color(0xFF18181B),
    error = Color(0xFFA70017),
    onError = Color(0xFFFFFFFF)
)

val DazzlerDark = darkColorScheme(
    primary = Color(0xFFC878E2),
    onPrimary = Color(0xFF000000),
    background = Color(0xFF060508),
    onBackground = Color(0xFFF3F3F7),
    surface = Color(0xFF131317),
    onSurface = Color(0xFFF3F3F7),
    error = Color(0xFFFF948C),
    onError = Color(0xFF000000)
)

val DazzlerTypography = Typography(bodyLarge = TextStyle(fontSize = 16.sp))
// Bind the chosen scheme and typography through MaterialTheme. Minimum touch target: 48dp.
