// Generated by Dazzler. Register licensed font assets before replacing system defaults.
import SwiftUI
import UIKit

enum DazzlerColors {
    static let primary = Color(uiColor: UIColor { traits in
        let hex: UInt32 = traits.userInterfaceStyle == .dark ? 0xC878E2 : 0x7C0D98
        return UIColor(red: CGFloat((hex >> 16) & 255) / 255, green: CGFloat((hex >> 8) & 255) / 255, blue: CGFloat(hex & 255) / 255, alpha: 1)
    })
    static let onPrimary = Color(uiColor: UIColor { traits in
        let hex: UInt32 = traits.userInterfaceStyle == .dark ? 0x000000 : 0xFFFFFF
        return UIColor(red: CGFloat((hex >> 16) & 255) / 255, green: CGFloat((hex >> 8) & 255) / 255, blue: CGFloat(hex & 255) / 255, alpha: 1)
    })
    static let background = Color(uiColor: UIColor { traits in
        let hex: UInt32 = traits.userInterfaceStyle == .dark ? 0x060508 : 0xFAF9FF
        return UIColor(red: CGFloat((hex >> 16) & 255) / 255, green: CGFloat((hex >> 8) & 255) / 255, blue: CGFloat(hex & 255) / 255, alpha: 1)
    })
    static let onBackground = Color(uiColor: UIColor { traits in
        let hex: UInt32 = traits.userInterfaceStyle == .dark ? 0xF3F3F7 : 0x18181B
        return UIColor(red: CGFloat((hex >> 16) & 255) / 255, green: CGFloat((hex >> 8) & 255) / 255, blue: CGFloat(hex & 255) / 255, alpha: 1)
    })
    static let surface = Color(uiColor: UIColor { traits in
        let hex: UInt32 = traits.userInterfaceStyle == .dark ? 0x131317 : 0xEEEEF4
        return UIColor(red: CGFloat((hex >> 16) & 255) / 255, green: CGFloat((hex >> 8) & 255) / 255, blue: CGFloat(hex & 255) / 255, alpha: 1)
    })
    static let onSurface = Color(uiColor: UIColor { traits in
        let hex: UInt32 = traits.userInterfaceStyle == .dark ? 0xF3F3F7 : 0x18181B
        return UIColor(red: CGFloat((hex >> 16) & 255) / 255, green: CGFloat((hex >> 8) & 255) / 255, blue: CGFloat(hex & 255) / 255, alpha: 1)
    })
    static let error = Color(uiColor: UIColor { traits in
        let hex: UInt32 = traits.userInterfaceStyle == .dark ? 0xFF948C : 0xA70017
        return UIColor(red: CGFloat((hex >> 16) & 255) / 255, green: CGFloat((hex >> 8) & 255) / 255, blue: CGFloat(hex & 255) / 255, alpha: 1)
    })
    static let onError = Color(uiColor: UIColor { traits in
        let hex: UInt32 = traits.userInterfaceStyle == .dark ? 0x000000 : 0xFFFFFF
        return UIColor(red: CGFloat((hex >> 16) & 255) / 255, green: CGFloat((hex >> 8) & 255) / 255, blue: CGFloat(hex & 255) / 255, alpha: 1)
    })
}

enum DazzlerType {
    static let body = Font.body
    static let heading = Font.title
}
// iOS only: semantic fonts preserve Dynamic Type. Minimum interactive size: 44pt.
