// Generated by Dazzler. Register licensed font assets before replacing system defaults.
import 'package:flutter/material.dart';

final dazzlerLight = ThemeData(
  useMaterial3: true,
  colorScheme: ColorScheme.fromSeed(
    seedColor: const Color(0xFF7C0D98),
    brightness: Brightness.light,
  ).copyWith(
    primary: const Color(0xFF7C0D98),
    onPrimary: const Color(0xFFFFFFFF),
    surface: const Color(0xFFEEEEF4),
    onSurface: const Color(0xFF18181B),
    error: const Color(0xFFA70017),
    onError: const Color(0xFFFFFFFF),
  ),
  scaffoldBackgroundColor: const Color(0xFFFAF9FF),
  textTheme: const TextTheme(bodyLarge: TextStyle(fontSize: 16)),
);

final dazzlerDark = ThemeData(
  useMaterial3: true,
  colorScheme: ColorScheme.fromSeed(
    seedColor: const Color(0xFFC878E2),
    brightness: Brightness.dark,
  ).copyWith(
    primary: const Color(0xFFC878E2),
    onPrimary: const Color(0xFF000000),
    surface: const Color(0xFF131317),
    onSurface: const Color(0xFFF3F3F7),
    error: const Color(0xFFFF948C),
    onError: const Color(0xFF000000),
  ),
  scaffoldBackgroundColor: const Color(0xFF060508),
  textTheme: const TextTheme(bodyLarge: TextStyle(fontSize: 16)),
);
// Bind theme/darkTheme in MaterialApp. Preserve MediaQuery text scaling and 48dp targets.
